# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wifi_remove.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

_b = sys.version_info[0] < 3 and (lambda x: x) \
     or (lambda x: x.encode('latin1'))

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='wifi_remove.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=_b(
        '\n\x11wifi_remove.proto\"!\n\x0ewifi_remove_v1\x12\x0f\n\x07service'
        '\x18\x01 \x01(\tb\x06proto3')
)

_WIFI_REMOVE_V1 = _descriptor.Descriptor(
    name='wifi_remove_v1',
    full_name='wifi_remove_v1',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='service', full_name='wifi_remove_v1.service', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[],
    serialized_start=21,
    serialized_end=54,
)

DESCRIPTOR.message_types_by_name['wifi_remove_v1'] = _WIFI_REMOVE_V1
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

wifi_remove_v1 = _reflection.GeneratedProtocolMessageType(
    'wifi_remove_v1',
    (_message.Message,),
    dict(
        DESCRIPTOR=_WIFI_REMOVE_V1,
        __module__='wifi_remove_pb2'
        # @@protoc_insertion_point(class_scope:wifi_remove_v1)
    ))
_sym_db.RegisterMessage(wifi_remove_v1)

# @@protoc_insertion_point(module_scope)
