# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: diagnostics.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x64iagnostics.proto\"{\n\x0e\x64iagnostics_v1\x12\x35\n\x0b\x64iagnostics\x18\x01 \x03(\x0b\x32 .diagnostics_v1.DiagnosticsEntry\x1a\x32\n\x10\x44iagnosticsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'diagnostics_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIAGNOSTICS_V1_DIAGNOSTICSENTRY._options = None
  _DIAGNOSTICS_V1_DIAGNOSTICSENTRY._serialized_options = b'8\001'
  _DIAGNOSTICS_V1._serialized_start=21
  _DIAGNOSTICS_V1._serialized_end=144
  _DIAGNOSTICS_V1_DIAGNOSTICSENTRY._serialized_start=94
  _DIAGNOSTICS_V1_DIAGNOSTICSENTRY._serialized_end=144
# @@protoc_insertion_point(module_scope)
